<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>
    
    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
       
    </style>

</head>

<body>

    <header>
        <h1 class="titulo-llamativo" align="center">El Faro</h1>
        <h6 align="center">Noticias de Colombia</h6>

    </header>
       <hr>
       <div class="container">
        <div class="row">
            <div>
                <div class="contenedor">
                    <h1><b>Escándalo en campaña de Petro: CNE destapó pagos no declarados a 35.000 testigos electorales</b></h1>
                    <h4>El Consejo Nacional Electoral se estaría preparando para presentar las primeras investigaciones,que podrían concluir en la formulación de cargos contra el mandatario nacional y el presidente de Ecopetrol
                    </h4>
                    <img src="../image/Noticia colombia.jpg" class="img-fluid mb-4" alt="Noticia Colombia">
                    <h6 class="mb-4">Campaña presidencial de Gustavo Petro habría pagado 60.000 pesos a los testigos electorales - crédito Johan Manolo Largo/Infobae</h6>
                    <h4> La campaña del presidente Gustavo Petro vuelve a estar en la mira de las autoridades electorales, luego de que se conociera que el Consejo Nacional Electoral (CNE) tiene pruebas de una presunta violación de los topes y la 
                         financiación prohibida de la campaña. <br>
                         La revista Semana conoció que los magistrados Álvaro Hernán Prada y Benjamín Ortiz se preparan para revelar cerca de un centenar de evidencias documentales, testimoniales y contables que apuntan a una posible violación de los límites de financiamiento electoral establecidos por la ley por parte de la campaña, además de la falta de reporte completo de ciertos ingresos al sistema Cuentas Claras. <br>
                         De acuerdo con la publicación bogotana, entre las pruebas más contundentes está que durante la campaña electoral “Petro Presidente” aproximadamente 35.000 testigos electorales recibieron un pago de 60.000 pesos, cada uno, durante el día de las elecciones, sumando así más de 1.000 millones de pesos en total.
                    </h4>
                </div>
            </div>
        </div>
    </div>

</body>
<footer class="mt-5">
    <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
</footer>