<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>
    
    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
        
    </style>

</head>

<body>

    <header>
        <h1 class="titulo-llamativo" align="center">El Faro</h1>
        <h6 align="center">Noticias de Ecuador</h6>

    </header>
       <hr>
       <div class="container">
        <div class="row">
            <div>
                <div>
                    <h1><b>Los ecuatorianos votan en una consulta popular que puede marcar el futuro político de Daniel Noboa</b></h1>
                    <h4>Deben dar su veredicto sobre once preguntas. Según el gobierno, su aprobación es vital para el combate al narcoterrorismo y el fomento de las inversiones.
                    </h4>
                    <img src="../image/noticia ecuador.jpg" class="img-fluid mb-4" alt="Noticia Ecuador">
                    <h6 class="mb-4">En menos de un año es la tercer vez que los ecuatorianos votan en una consulta popular. En el mismo periodo también votaron por autoridades municipales y por un nuevo presidente y legisladores. (EFE/Santiago Fernández)
                    </h6>
                    <h4>Este domingo será la tercera vez en poco más de un año que los ecuatorianos acudirán a las urnas a votar por una consulta popular. <br>
                        En febrero de 2023 ya lo hicieron con la impulsada por el expresidente Guillermo Lasso, que perdió aparatosamente, y en la consulta sobre dejar el petróleo bajo tierra en el Yasuní. Este domingo, 13 millones de electores deberán votar por once preguntas que, según el gobierno de Daniel Noboa, deben aprobarse para combatir a las bandas narcoterroristas y atraer inversiones. Los ecuatorianos en el exterior también podrán votar en los consultados salvo en Israel, México, Rusia, Bielorrusia y Nicaragua. Nuevamente, se preguntará a los ecuatorianos si están de acuerdo con la extradición de connacionales desde Ecuador, una pregunta que perdió con Guillermo Lasso pero que podría ganar con Noboa. <br>
                        Hace una semana parecía que el Ejecutivo tenía casi asegurada la victoria en la consulta y referéndum, pues los sondeos de opinión ubicaban la popularidad de Daniel Noboa en el 70%. <br>
                        Los estudios sobre los plebiscitos en América Latina demuestran que los resultados de dichas consultas están vinculadas al nivel de apoyo del convocante, generalmente los gobernantes, salvo en Uruguay donde las consultas son convocadas por la ciudadanía. En ese contexto, esta era la primera prueba de fuego para Noboa, que piensa elegirse en un periodo completo en 2025.
                    </h4>
                </div>
            </div>
        </div>
    </div>

</body>
<footer class="mt-5">
    <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
</footer>