<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>
    
    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
           
    </style>

</head>

<body>

    <header>
        <h1 class="titulo-llamativo" align="center">El Faro</h1>
        <h6 align="center">Noticias de España</h6>

    </header>
       <hr>
       <div class="container">
        <div class="row">
            <div>
                <div class="contenedor">
                    <h1><b>Elecciones País Vasco 2024, en directo: sigue minuto a minuto la jornada electoral</b></h1>
                    <h4>Los comicios se presentan muy reñidos, con la duda de si el partido que más escaños logrará será el PNV, el tradicional ganador en las últimas décadas o Bildu, que aspira a arrebatarle la primera plaza.
                    </h4>
                    <img src="../image/noticia españa.jpg" class="img-fluid mb-4" alt="Noticia España">
                    <h6 class="mb-4">En menos de un año es la tercer vez que los ecuatorianos votan en una consulta popular. En el mismo periodo también votaron por autoridades municipales y por un nuevo presidente y legisladores. (EFE/Santiago Fernández)
                    </h6>
                    <h4>13:54 hsHoy
                        Cierran los colegios electorales: comienza el recuento
                        A las 20:00 horas han cerrado los colegios electorales, por lo que a continuación comenzará el recuento de los votos, y en pocas horas se conocerá el resultado final.
                        Los primeros sondeos a pie de urna anticipan una situación muy igualada entre PNV y Bildu.
                        13:51 hsHoy
                        El PSE-EE ve “con optimismo” el aumento de la participación
                        El PSE-EE ha acogido “con optimismo” el aumento de la participación en las elecciones vascas al que apuntan los datos de los que se dispone hasta el momento, dado que “el electorado nacionalista es el más fácilmente movilizable” y, por tanto, “a más participación, más votos del PSE”.
                        En una comparecencia en el Bizkaia Aretoa de Bilbao, donde el PSE-EE está realizando el seguimiento de la jornada electoral, los miembros de la Ejecutiva socialista Ekain Rico y Pau Blasi han valorado que la jornada electoral se está desarrollando sin incidencias “notables” y se está “ejerciendo con normalidad el derecho a voto”, lo que es “una buena noticia”.
                        Finalmente, han esperado que, en el último tramo de la jornada hasta el cierre de los colegios a las 20 horas, “un buen número se acerque a ejercer su derecho a voto”.
                        13:11 hsHoy
                        La participación a las 18.00 se sitúa en un 51%
                        Los datos de participación hasta las 18.00 horas ascienden al 51% del censo, según ha informado este domingo el Gobierno vasco. En 2020, la participación a las 17.00 horas fue la más baja desde 1994 con un 36,2%, debido a que las elecciones se celebraron en plena pandemia. Los datos también reflejan una movilización superior a la de 2016, aunque no es posible hacer una comparación exacta porque se ha cambiado la metodología.
                        Por territorios, en Bizkaia han votado el 51,9% de los electores. En Gipuzkoa, el dato es del 50,7% y en Álava, del 48,7%. En cuanto a las capitales, en Bilbao ha acudido a las urnas ya el 50,3% del electorado. En San Sebastián, la proporción es del 51,5%, y en Vitoria, del 47,8%.
                        Estas cifran anticipan una afluencia a las urnas más elevadas que en las citas precedentes, pero sin que se pueda hablar de movilización masiva, ya que la abstención sigue siendo muy relevante.
                        12:19 hsHoy
                        Cuántos diputados hacen falta para la mayoría absoluta en las elecciones del País Vasco
                        Esta noche se podrá determinar quién estará al frente del Gobierno autonómico.
                    </h4>
                </div>
            </div>
        </div>
    </div>
    

    






</body>
<footer class="mt-5">
    <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
</footer>