<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>

    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
        .titulo-llamativo {
            font-family: 'Honk', sans-serif;
            font-size: 6rem;
        }

        .contenedor {
            max-width: 3000px;
            /* Ancho máximo del contenedor */
            margin: 0 auto;
            /* Centra el contenedor horizontalmente */
            padding: 0 40px;
            /* Agrega un relleno a los lados del contenedor */
        }
    </style>

</head>

<body>

    <header>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 align="center"> <img src="../image/simbolo el faro.jpg" ></h1>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <h1><b>Crisis en Venezuela</b></h1>
        <hr>
        <section id="inicio">
            <div class="row">
                <div class="col-lg-6">
                    <!-- Contenido de la noticia grande -->
                    <h3><b>Edmundo González Urrutia anuncio su candidatura a la presidencia de Venezuela</b></h3>
                    <h5>El diplomático venezolano dijo que aceptaba el inmenso honor y responsabilidad tras
                        ser elegido por la coalición antichavista Plataforma unida Democrática para reemplazar
                        a la inhabilitada María Corina Machado en los comicios del próximo 28 de julio.</h5>
                    <img src="../image/noticia venezuela grande.jpg" class="img-fluid">
                </div>
                <div class="col-lg-6">
                    <!-- Contenido de las noticias pequeñas -->
                    <div class="noticias-pequenas">
                        <div class="row">
                            <!-- Contenido de la primera noticia pequeña -->
                            <div class="noticia-pequena">
                                <h5><b>La historia de El rojo, el intocable y poderoso familiar de El Aissami en
                                        Apure.</b></h5>
                                <h7>Alex Aamer es primo de Rodaima Amer; esposa del ex ministro de petróleo de
                                    Venezuela.
                                    Su inmensa fortuna va aceitando el paso a través de altos oficiales de
                                    la fuerza armada y dirigentes políticos sin distingo ideológicos, solo el culto al
                                    dinero.</h7>
                                <img src="../image/noticia venezuela pequeña 1.jpg" class="img-fluid">
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <!-- Contenido de la segunda noticia pequeña -->
                            <div class="noticia-pequena">
                                <h5><b>Que hay detrás del doble juego de Gustavo Petro con las elecciones de
                                        Venezuela.</b></h5>
                                <h7>El mandatario colombiano propuso un plebiscito simultaneo a las presidenciales
                                    mientras
                                    al mismo tiempo se reunió con el candidato pseudo opositor avalado por el régimen..
                                </h7>
                                <img src="../image/noticia venezuela pequeña 2.jpg" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <hr>

        <div class="row">
            <div class="col-md-12">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="../index.php" class="btn btn-secondary me-md-2" type="button">atras</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>


<footer class="mt-5">
    <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
</footer>

</html>