<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>

    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
        .titulo-llamativo {
            font-family: 'Honk', sans-serif;
            font-size: 6rem;
        }
    </style>

</head>

<body>

    <header>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 align="center"> <img src="../image/simbolo el faro.jpg" ></h1>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <h1><b>Guerra en Medio Oriente</b></h1>
        <hr>
        <section id="inicio">
            <div class="row">
                <div class="col-lg-6">
                    <!-- Contenido de la noticia grande -->
                        <h3><b>Netanyahu prometió incrementar la presión militar y diplomática sobre Hamas</b></h3>
                        <h5>En un mensaje emitido antes de la Pascua judía, el premier declaró que “la ausencia”
                            de los rehenes secuestrados por el grupo terrorista “solo fortalecerá
                            la determinación del país para recuperarlos”</h5>
                        <img src="../image/noticia grande iran.jpg" class="img-fluid">
                        <h6> El primer ministro israelí, Benjamin Netanyahu, convoca
                            la reunión semanal del gabinete en el Ministerio de Defensa en
                            Tel Aviv, Israel. 7 de enero de 2024 (REUTERS/Ronen Zvulun/Pool/Archivo) </h6>
                </div>
                <div class="col-lg-6">
                    <!-- Contenido de las noticias pequeñas -->
                    <div class="row">
                        <!-- Contenido de la primera noticia pequeña -->
                        <div class="noticia-pequena">
                            <h5><b>Milei consolida el giro geopolítico y ejecuta una modernización de
                                    las Fuerzas Armadas para lograr el ingreso a la OTAN.</b></h5>
                            <h7>El Presidente necesita avales diplomáticos para avanzar
                                en el proceso de aprobación que le permita a Argentina ser “socio global”
                                de la alianza militar más poderosa del mundo. Instruyó a Luis Petri para
                                buscar el consenso de las potencias occidentales</h7>
                            <img src="../image/pequeña 1 iran.jpg" class="img-fluid">
                        </div>
                        <hr>
                        <!-- Contenido de la segunda noticia pequeña -->
                        <div class="noticia-pequena">
                            <h5><b>La tecnología bélica utilizada por Israel en el ataque limitado
                                    a Irán abrió una etapa inédita en la crisis de Medio Oriente.</b></h5>
                            <h7>La ofensiva aérea israelí contra blancos iraníes se caracterizó
                                por su precisión para golpear sin causar daños colaterales,
                                en un complejo escenario que incluye la negociación por los rehenes,
                                la fractura del mundo árabe y las dudas de Biden sobre los próximos pasos de
                                Netanyahu.</h7>
                            <img src="../image/noticia pequeña 2 iran.jpg" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <hr>
        <div class="row">
            <div class="col-md-12">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="../index.php" class="btn btn-secondary me-md-2" type="button">atras</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>





<footer class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col">
                <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
            </div>
        </div>
    </div>
</footer>