<!DOCTYPE html>
<!--doctype es una etiqueta que no necesita cierre y cuya funcion es facilitar informacion al servidor web que aloja pagina-->
<html lang="en">
<!--HTML es una etiqueta par  y es la etiqueta que cierra todo el documento HTML-->

<head>
    
    <!-- es una etiqueta par , definira la cabecera del documento  y contiene informacion del mismo (meta datos scripts, estilos 
         ubicacion de documentos de estilos, titulo de la pagina, entre otros)-->
    <meta charset="UTF-8">
    <meta name="author" content="noticias a tu alcance">
    <!--la descripcion del sitio se descrive aqui -->
    <meta name="description" content="diario de noticias actuales , deporte, negocios y todo lo que necesites saber ">
    <!--title=es el nombre que va en el costado superior izquierdo de la pagina -->
    <title>Diario El Faro</title>
    <!--link= es el icono que va en el costado superior izquierdo de la pagina-->
    <link rel="icon" type="image/png" href="icon/faroicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <script src="js/EnviarCorreo.js"></script>

    <style>
        .titulo-llamativo {
           font-family:  'Honk', sans-serif;
           font-size: 6rem;
        }
        .contenedor {
        max-width: 3000px; /* Ancho máximo del contenedor */
        margin: 0 auto; /* Centra el contenedor horizontalmente */
        padding: 0 190px; /* Agrega un relleno a los lados del contenedor */
         }
           
    </style>

</head>

<body>

    <header>
        <h1 class="titulo-llamativo" align="center">El Faro</h1>
        <h6 align="center">Noticias de Perú</h6>

    </header>
       <hr>
       <div class="container">
        <div class="row">
            <div>
                <div class="contenedor">
                    <h1><b>Dina Boluarte no volverá a tener “viajes exploratorios” porque “es consciente que cometió errores”, explicó el canciller</b></h1>
                    <h4>Ministro de Relaciones Exteriores, Javier González-Olaechea, descartó que la presidenta del Perú vuelva a salir al extranjero a menos que sea necesario. Medida se da tras millones de soles gastados durante el 2023 en viajes para ella y toda su comitiva
                    </h4>
                    <img src="../image/noticia ecuador.jpg" class="img-fluid mb-4" alt="Noticia Ecuador">
                    <h6 class="mb-4">Presidenta se acogerá nuevamente a la ley de presidencia remota para 
                        visitar Italia, Alemania y el Vaticano. Gastos ascienden a más de 300.000 soles.
                    <h4>“Los viajes exploratorios le corresponden al canciller”. Con esta breve frase, 
                        el ministro de Relaciones Exteriores, Javier González-Olaechea, descartó la
                         posibilidad de que la presidenta Dina Boluarte viaje fuera del país, a menos 
                         que se trate de una situación que exija su presencia. Así se ha detallado en 
                         la última entrevista concedida por el titular de la cancillería para El Comercio,
                          en la que deja clara una nueva política de Estado sumamente distinta a la que expuso
                           su antecesora, la exministra Ana Cecilia Gervasi; las salidas —a veces hasta 
                           injustificadas— de la mandataria al extranjero.
                    </h4>
                </div>
            </div>
        </div>
    </div>
    









    </div>

    






</body>
<footer class="mt-5">
    <h5>Realizado en 2024 por Estudiantes Jean Rodriguez, Roberto Vega</h5>
</footer>